In [1]:
# gj
import pandas as pd
import glob

# 读取 parquet 文件
# 匹配目录下所有 parquet 文件
files = glob.glob("/mnt/datasets/liyaqi/Clotho/*.csv", recursive=True)

# 逐个读取并拼接
df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)

display(df)

,file_name,caption_1,caption_2,caption_3,caption_4,caption_5
0,Santa Motor.wav,A machine whines and squeals while rhythmicall...,A person is using electric clippers to trim bu...,Someone is trimming the bushes with electric c...,The whirring of a pump fills a bladder that tu...,"While rhythmically punching or stamping, a mac..."
1,Radio Garble.wav,A radio dispatcher and an officer are communic...,Communication with a walkie-talkie with a lot ...,A discussion with a walkie-talkie with a consi...,People talking through a walkie-talkie with ba...,The walkie-talkie the people are talking throu...
2,Radio Fuzz for Old Radio Broadcast FF233.wav,A radio tuner has been positioned in between r...,A transistor radio is being played on a statio...,A transistor radio is on a station that is not...,Radio static makes a constant hum with a high ...,Static coming from a radio that is in between ...
3,toy rattle 2.wav,A person winding up a device and then jingling...,A socket wrench that is tightening a bolt.,An object is tightened and then metallic objec...,"Before keys are jangled on their chain, someon...",Someone is spinning around a lock with a dial.
4,Blade Big.wav,A person is pulling silverware out of the dish...,A person removes a knife from its holder then ...,A person taking a knife out of its holder and ...,Metal sliding together such as swords or knives.,The metallic clang of swords and knives striki...
...,...,...,...,...,...,...
3933,"Crickets calling at night, UK.wav","As the wind blows steadily, many crickets chirp.",Crickets chirp back and forth in the night air,Crickets chirp in the background as a soft win...,Crickets chirp in the background as a soft win...,Multiple crickets chirping with a steady wind ...
3934,"Rain On Town Square, South Germany.wav",As rain falls continuously to the ground a man...,People are speaking when it is raining outside.,Rain is falling outside while people are talking.,Two people are outside talking while it is rai...,Two people are talking outside while it is rai...
3935,amazon 04.wav,A bird is singing in the background as an engi...,A bird is singing in the background while an e...,An engine runs as birds chirp and sing in the ...,An engine runs as birds chirp and sing.,The birds are singing while an engine is runni...
3936,steps come and go on stone ground in a village...,A person is walking on a hard surface while bi...,A person is walking on a hard surface while bi...,Birds chirp while a person walks on a hard sur...,Someone walks across a hard surface as birds c...,The chirping and singing of many birds is foll...
3937,Heavy rain - some people 2.wav,A heavy rain coming down outside with people t...,A heavy rain falls outside while people talk i...,Rain falling while people talk in the background.,Rain is falling as people talk in the background.,Water is running while people are talking thro...

In [3]:
import os

wavs = df["file_name"].tolist()
for wav in wavs:

    # 原始文件路径
    src_path = "/mnt/datasets/liyaqi/Clotho/development+evaluation/"+wav
    # 输出随机文件路径
    dst_path = "/mnt/datasets/ExpandedClotho/wavs/"

    # 获取原始文件大小（字节数）
    size = os.path.getsize(src_path)

    for i in range(5):
        # 生成同样大小的随机字节
        random_data = os.urandom(size)
        name, ext = os.path.splitext(wav)
        new_name = f"{name}({i}){ext}"
        # 写入新文件
        with open(dst_path+new_name, "wb") as f:
            f.write(random_data)

In [12]:
newdf=pd.DataFrame(columns=df.columns)
import random
import string

for index, row in df.iterrows():
    filename=row["file_name"]
    captions=[row["caption_1"],row["caption_2"],row["caption_3"],row["caption_4"],row["caption_5"],]

    for i in range(5):
        name, ext = os.path.splitext(filename)
        new_name = f"{name}({i}){ext}"
        new_captions=[]
        for j in range(5):
            new_captions+=[''.join(random.choices(string.ascii_letters, k=len(captions[j])))]
        newdf.loc[len(newdf)]=[new_name]+new_captions

display(newdf)

,file_name,caption_1,caption_2,caption_3,caption_4,caption_5
0,Santa Motor(0).wav,FqstmSknjlfCrSPKIHSEjzFmKhzsVXJWzkzOmUNfQnAiSr...,WmLJwnYzjbkpgoowxSMXdYSeryMYSfgBHRcmHlGfvqfxNB...,vErzfumOXCWrkNgZRMvnfxNXgaqqvEYGCYzWDEUkeEoDPd...,pDqsGklpbSzRQKjjEzlSTuxfuZFDONDbJgitMsbPktOFYp...,mLVDzQejSbxPdYZGbeCVbnHtMkVIkQDuxTgvbDYQMxAjrO...
1,Santa Motor(1).wav,RALYZAsBiPbcrxgdcMBszjqPCmUqrmvQBHHOSAUTdDzITB...,DCUIhFgZjNhWtppDCWLAfOlVfpmULljRQRRxzAZmKukvzt...,eSDxcdtAHlfZNyLyFyjgrvwsFmSNGSRiZKJOqoRazXWOPg...,EVpMVjwpAOjXoLcCxpEpUULdPvkMrECpbEYBnGShnRPZER...,qwVNcuqitzSLgRJIOgaHSoTTBEAMstYIgYzMxaUjngCycq...
2,Santa Motor(2).wav,JwgVHRWOYSVAesBEpYRwaccPGKFAnmvnMoFqFkmimtXEqu...,hiTuLnKxAtpQBkWTuHiWmumkyGUzriEGQsPyKhVXpWwMMa...,iTOHUskcbEtKnmZskwfyMJlRARCKKSKlECKQLmjAhilpfn...,xUGzCVkUASuISYLBHMxwvRckgouuPFwChelOKNCCWOVVMd...,qhoBZedmzVsbCRFJdNtbvHOlbBCqiQKxMkInKbOAviJQSO...
3,Santa Motor(3).wav,lYOlfgBDZYEPHbXRvbYVjABnKUWSZzgqpoKdpxdqeCPwHV...,QAOSmeogxOkHrlOpHhqHQClmlCfvCZhqVAdmMEyXbYNjkg...,quImRdfxiLwZcdmHoPIkKNmcQawzxduoEMwNrMVzqJqUaQ...,hGtCwuvLlhghkXFlBEDXJsvQyiTtgwxBwdctQoWadTPxdr...,WfDafNXeULTRxTBomOqrIpuHaAWFVroUKbMHaudXHCwxLJ...
4,Santa Motor(4).wav,sHEFRMiMEebXMrsHBSCpIwQmILIQfhwpucgIasrOYYqojn...,lcPyutXedzRSRQtZjHGclWmncGmEnpsgrjVdhSrwTnPSkl...,kZgTEKFtfMyWDAUEkQcrgECufAWCcmyKRBVErIUCufwxds...,DOvioYJxUazlSNfVvKKkyckwgSZGZEVCuTHvWZYblmYZpw...,ZqfPcstRMeZwifdxaTIEADGxNnhxyBUpDyZejwLeHRYZFm...
...,...,...,...,...,...,...
19685,Heavy rain - some people 2(0).wav,fOzZwEuHAsTOpYHVgZekYcQttIaoEJDJIbazUgXNjguoDy...,NrphIlFSiCNXNQRNgYjpeZMmZDrLafzUkHXIVnsMcSEarw...,mwqrhQXvFAvTTQYBNuVnvtmeyqDsnxdIhJTTmHDjYjGnVVcrD,wdMJicOiwZTFGrZUsNDBRtXbyHVGlSddLtqsBMRkvCWzkQWMh,ANhHSVSAoREJQRPVaDSBUzPqIjmfcfUeCSHaAHcJZZbSKe...
19686,Heavy rain - some people 2(1).wav,zRkbLCxAIAJBFRpGlgOKviOZMRpIiLJrSxafpAQAMCOPnv...,nzVeSCTcQYBYSwYSrflRqAwKXttWkxXXqTIPMjRhuYDdvV...,vhbhNiDaxGErfWkfHVqvMyjOODhnQqJksNewmvFmjrrScDkxX,sKsaBMpQryYkbEjYQyjZpWNVJbwKlPNDOoPHMgNVHBbQuZtFc,LQpGfalAbsrLVAFxfFKFLBvSxUhrYbgNKreKlHzegpHDes...
19687,Heavy rain - some people 2(2).wav,jpESofBytuAIJMqTpIKCXsnQHTtkoHiedAYNXMxrOPpYjU...,VZvIhGkpaRIgjKxSyRlFFrXCFeICoTsdATTTfszgQLFlTY...,thrAvUlwbJVMTEEoVhhyZKIVEQHddHvekjkHXyQWTqffRdErQ,jUqkZwEhFwSpqEyApzRKUkmcTPkDJUYPBcWriZfkagOObCfeA,mjrHSoJabETDOUKVGFKGXNEwlKkGcTJqVNyVlOCtMZccat...
19688,Heavy rain - some people 2(3).wav,FkfRzKmCrVmWSDXdYvqfkeZBbCUoVPZGwosSbJZYiXnyoQ...,OnVhndGbNtSUGPVZSTkheKIjNgKVxxVupNGinHecmbIxzO...,bpwWTZbvYnYNMidgHCwhZpAWujTMQpmkCrbFCPVPHTcDcoAkS,DCpPxDknIXoRntKbnMrfJfxuyfuCbsCxTrCJjApAWGtUyMjya,uqbsJhkNDoZFDejhziPVvHKBELnoZKICoOSvoPmmIDKqoD...
19689,Heavy rain - some people 2(4).wav,LWqLbqcgKUzGfvXSaCaHJCkmulnbDKdRYnBFhqPIuytzSX...,utyNiQiOXLYqBAiyFhRzvYuiKspaNkNYadtgOxEnqWztIG...,CfigXDGxGFRkdnXLMPslmnSbQVjzqPyKfsiMgFgBAQrBQNXhd,LVOmFOkZttzjScXbMRfVynSKinTwQTlepCkrZpxCWrWUcfQTQ,zfjezuHmmgvrHlhzZrGlNDDYKckgAjOSmDxfwDisamfpbN...

In [13]:
newdf.to_csv('/mnt/datasets/ExpandedClotho/ExpandedClotho.csv', index=False)

In [14]:
images = newdf["file_name"].tolist()
captions=[newdf["caption_1"].tolist(),newdf["caption_2"].tolist(),newdf["caption_3"].tolist(),newdf["caption_4"].tolist(),newdf["caption_5"].tolist(),]
res = {"image_path":[],"image_shape":[],"image_tensor_size":[],"image_file_size":[],"compression_rate":[],"image_caption":[],"image_caption_size":[]}

image_dir = "/mnt/datasets/ExpandedClotho/wavs"

for i in range(len(images)):
    if i % round(len(images)/4) == 0:
        print(i/len(images))

    image_path = images[i]
    image_full_path = os.path.join(image_dir, image_path)
    for j in range(5):
        res["image_path"].append(image_path)
        res["image_shape"].append(0)
        # res["image_tensor_size"].append(image_tensor_size)
        res["image_tensor_size"].append(0)
        image_file_size = os.path.getsize(image_full_path)
        res["image_file_size"].append(image_file_size)
        # res["compression_rate"].append(f"{image_tensor_size/image_file_size:0.2f}")
        res["compression_rate"].append(0)
        image_caption = captions[j][i]
        res["image_caption"].append(image_caption)
        image_caption_size = len(image_caption)
        res["image_caption_size"].append(image_caption_size)

out = pd.DataFrame(res)
# out.to_csv("MSRVTT_sample.csv",index=False)

display(out)

0.0
0.2499746063991874
0.4999492127983748
0.7499238191975622
0.9998984255967496

,image_path,image_shape,image_tensor_size,image_file_size,compression_rate,image_caption,image_caption_size
0,Santa Motor(0).wav,0,0,1866796,0,FqstmSknjlfCrSPKIHSEjzFmKhzsVXJWzkzOmUNfQnAiSr...,69
1,Santa Motor(0).wav,0,0,1866796,0,WmLJwnYzjbkpgoowxSMXdYSeryMYSfgBHRcmHlGfvqfxNB...,51
2,Santa Motor(0).wav,0,0,1866796,0,vErzfumOXCWrkNgZRMvnfxNXgaqqvEYGCYzWDEUkeEoDPd...,54
3,Santa Motor(0).wav,0,0,1866796,0,pDqsGklpbSzRQKjjEzlSTuxfuZFDONDbJgitMsbPktOFYp...,79
4,Santa Motor(0).wav,0,0,1866796,0,mLVDzQejSbxPdYZGbeCVbnHtMkVIkQDuxTgvbDYQMxAjrO...,70
...,...,...,...,...,...,...,...
98445,Heavy rain - some people 2(4).wav,0,0,2054070,0,LWqLbqcgKUzGfvXSaCaHJCkmulnbDKdRYnBFhqPIuytzSX...,71
98446,Heavy rain - some people 2(4).wav,0,0,2054070,0,utyNiQiOXLYqBAiyFhRzvYuiKspaNkNYadtgOxEnqWztIG...,63
98447,Heavy rain - some people 2(4).wav,0,0,2054070,0,CfigXDGxGFRkdnXLMPslmnSbQVjzqPyKfsiMgFgBAQrBQNXhd,49
98448,Heavy rain - some people 2(4).wav,0,0,2054070,0,LVOmFOkZttzjScXbMRfVynSKinTwQTlepCkrZpxCWrWUcfQTQ,49
98449,Heavy rain - some people 2(4).wav,0,0,2054070,0,zfjezuHmmgvrHlhzZrGlNDDYKckgAjOSmDxfwDisamfpbN...,53

In [15]:
# 提取数字并转换为整数类型
out['numeric_id'] = out['image_path']

# 按数字升序排序
sorted_df = out.sort_values(by='numeric_id', ascending=True)

# 生成新CSV文件（删除辅助列）
sorted_df.drop(columns=['numeric_id']).to_csv('/home/llm/experiment/dataset_Analysis_Modeling/processed_datasets/ExpandedClotho_sort.csv', index=False)